### ISSUE TITLE
Add support for Sabre ESS9018

### ISSUE THREAD

**Issue by koalo** [koalo/linux#1]
Copied from forum, by steveha:

---

The main difference between them is ESS9018 is running on 64fs bit clock I2S and TDA1541A only does 48fs. Also, ESS9018 can support higher sampling rates like 176.4 khz or 192 khz. Particular for 176.4 khz, I did aware there is a custom mpd to stream native DSD signals (i.e. not DoP) over I2S. 

Main tasks:
- Enable support for higher bitrates in the i2s driver
- Write dummy driver for ESS9018

**Comment by koalo** [comment]
Steve, do your boards run as I2S master?

**Comment by steveha8838** [comment]
I think it should be I2S master.  I bought the boards in pair - transmitter and receiver.  The transmitter board is mounted on raspberry pi.  The I2S signals alway sends from transmitter to receiver.  Hope this help.

**Comment by koalo** [comment]
The interesting part is the clock: Is that generated by your board (good) or should it be generated by the raspberry (not so good)?

**Comment by steveha8838** [comment]
I have no tool to measure how good is the clock of raspberry.  But based on the listening test of TDA1541A, its clock should be good enough.  For ESS9018,  some documents has shown the DAC itself will resample the incoming signals according to the board's clock. So, it will suggest to get somthing first that can be recognised by ESS9018.

**Comment by steveha8838** [comment]
Latest update.  After compilation of 06 May Version.   44.1/16 can be recognised on both TDA1541A and ESS9018.  For ESS9018, anything above 441.khz generated noise only.  What have you done to 44.1khz ?

**Comment by koalo** [comment]
Done by ca53c999846cb1ce8b1bacedcd6e652b6b0a9792

Please test it!

**Comment by steveha8838** [comment]
It's my pleasure. Just don't laught at me. I leant how to compile the kernel within raspberry a week ago.
Your efficiency simply faster than my leaning curve.

**Comment by koalo** [comment]
It wasn't meant to be an order ;-) Take your time and let me know when I can help you with something.

For me 32 bit does not sound perfect, but this could be because of my source material.

**Comment by steveha8838** [comment]
I am eager to do it.  Just want to provide you feedback at the earliest.

**Comment by steveha8838** [comment]
Finally, I have my 1st trial with the following results :-
- all modules (TDA1541a and ESS9018) can be loaded sucessfully;
- All  sample frequencies up to 192Khz can be played on Wyred DAC2 with sound (no noise);
  - Samples frequences matched with hw_params
  - However 
    while playing 44.1khz song,  LED display on DAC2 showing 88.2khz
    while playing 96kkhz song, LED display on DAC2 showing 192khz
    while playing 192khz song, LED display on DAC2 showing '----'
- Can't test songs over 192khz, it seems you have set the limit to 192khz
  FYI, DXD files can be up to 352.8khz or 384khz
- Tomorrow, I will investigate the sound quality.

Hope this help

**Comment by steveha8838** [comment]
The sound quality is relly good on my Wyred DAC2.  At the same times, I have performed some tests using mplayer.   By default, mplayer will pick S16_LE.  I have no problem to stream radio contents to my dac and dac can display the correct sampling frequency.  I will say 16 bits model is quit perfect.

To enforce S32_LE within mplayer, I need to specific 'plughw' instead of 'hw' on command line. 

e.g. mplayer -ao alsa:device=plughw=1.0  /music/transfer/192.wav

The behavior is similar to that of mpd.  The I2S signals have been upsampled.

One more point I want to add :- when streamling DSD contents, the bit clock has been set correctly to 176.4khz using the current prototype. The missing part is to treat LRCLK as data. May be I am too optimistic
at this moment.

**Comment by koalo** [comment]
Thank you so much for testing!!

> However while playing 44.1khz song, LED display on DAC2 showing 88.2khz while playing 96kkhz song, LED display on DAC2 showing 192khz while playing 192khz song, LED display on DAC2 showing '----'

That could correspond to issue #10, but I don't know. 
Although, I measured the correct frequencies with a scope.

> Can't test songs over 192khz, it seems you have set the limit to 192khz FYI, DXD files can be up to 352.8khz or 384khz

ALSA doesn't support sampling rates above 192kHz. At least, there is no corresponding macro. I am sorry!

> To enforce S32_LE within mplayer, I need to specific 'plughw' instead of 'hw' on command line.

For me mplayer automatically chooses 32 bit as long as the audio file itself is 32 bit. Although, for 24 bit files it uses 16 bit. What is the bit depth of your files?

> One more point I want to add :- when streamling DSD contents, the bit clock has been set correctly to 176.4khz
> using the current prototype. The missing part is to treat LRCLK as data. May be I am too optimistic
> at this moment.

Sorry, I don't understand what you want to do :-(

**Comment by steveha8838** [comment]
For mplayer, I am testing it with 24bits file.  The last part is related to DSD streaming vis I2S.  It makes a big differenc to PCM streaming.  It guess it should be out of scope.  I have been playing Raspberry PI with Wyred DAC2 for last two days. They are running smoothly and I have nothing to report further.

**Comment by koalo** [comment]
This is really great to hear that it runs smoothly!
DSD content could be possible in some way, but as the Raspberry Pi has no direct support for that I think we wouldn't be happy with that.

I think I can close this issue now.
