### ISSUE TITLE
Possible wrong clock freq for MASH mode

### ISSUE THREAD

**Issue by aberindei** [koalo/linux#10]
Is this correct?

linux / sound / soc / bcm2708 / bcm2708-i2s.c

half_frame = data_length_2; /_ overwrite half frame length, because the above trick is not needed _/
target_frequency = sampling_rate_half_frame*2;

This gives a bitclock of 64_fs for 16 bit and 128_fs for 32bit samples, not 32_fs for 16 bit and 64_fs for 32bit!

**Comment by koalo** [comment]
Thank you for reporting this!

> This gives a bitclock of 64_fs for 16 bit and 128_fs for 32bit samples

You are absolutely right! Although, this is intended :-) I could not find any reliable information about this. Therefore, I measured what comes out of my WM8731 and that is 64*fs for 16 bit. Do you have any information how this should be or maybe a codec that has problems with this settings?

**Comment by steveha8838** [comment]
I don't know how to fix it.  Just want to share the findings on my dacs (TDA1541A and ESS9018) after changing the above half_frame and target_frequency.

a) When amending half_frame = data_length

1) Modprode tda1541a

```
- TDA1541A sounds normal;
- ESS9018 sounds noisy (may be due to ESS9018 can't support 32fs)
```

2) Modprode ess9018
    - TDA1541A sounds normal;
    - ESS9018 sounds normal and my LED's display shows corrected sampling frequency 
       When I force ESS9018 to operate on S16_LE, noise came back againg;

It seem S16_LE operates at 32fs and S32_LE operates at 64fs

b) When amending target_frequency = sampling_rate \* half_frame, sound becomes slow motion  (not acceptable on both dacs).

I don't know are there any side-effects when changing the above.

**Comment by steveha8838** [comment]
BTW, what is the best fs to run TDA1541A ?

**Comment by aberindei** [comment]
I think the somehow standard bitclock these days would be 64_fs for all bitdepths (like WM8731 run in master mode and other/most of the codecs do).
After doing some testing I found that settings for 32_fs bitclock for 16 bit and running the BCM2835 I2S interface in slave mode and codec providing a frame of 64 clocks would not work.The reason for this is how the BCM2835 I2S interface works , especially frame sync when is programmed with frame length != 0 (page 121).
The conclusion would be that 64_fs or higher bitclock will work in master or slave mode ,MASH mode, but higher bitclock than  64_fs might not be supported  by some codecs/DACs thus will be safer to go with 64*fs for 16 and 32 bit.

**Comment by koalo** [comment]
Thank you so much for this explanation!
This totally makes sense. In that case I will use 64*fs for all bit depths in MASH mode (at least until someone claims he has a problem with that).

By the way: This frame length = 0 issue is very strange. "However, this creates a short timing path that will
corrupt the PCM_DOUT for one specific frame/channel setting." At least they could have written which one it is....

**Comment by steveha8838** [comment]
Hi adi-berindei

As you have tested I2S slave mode, I am going to try it out.  Should I feed in raspberry with both BCLK and WS or just BCLK ?

Regards
Steve

**Comment by koalo** [comment]
> Should I feed in raspberry with both BCLK and WS or just BCLK ?

Both - otherwise the Raspberry doesn't know where to start.

**Comment by steveha8838** [comment]
Thank you.

**Comment by koalo** [comment]
I have changed this to fixed 64*fs. I hope this fixes this.
