### ISSUE TITLE
bitclock not consistent (32xFS, 64xFS)

### ISSUE THREAD

**Issue by ghost** [koalo/linux#18]
bcm2708-i2s.c: Samplerates, that uses MASH mode use BCLK=64xFS, other 32xFS. The default setting should be 64xFS for all modes.
It would also help, if this would be configurable by the sound card driver. The driver should be able to initialize the clock that it needs.

--- ./sound/soc/bcm2708/bcm2708-i2s.c   2013-09-13 20:40:45.630200001 +0200
+++ ./sound/soc/bcm2708/bcm2708-i2s.c.orig  2013-09-13 22:40:09.582200003 +0200
@@ -476,9 +476,6 @@
     \* variance. To minimize that it is best to have the fastest
     \* clock here. That is PLLD with 500 MHz.
     */
-   // bug fix ? Daniel Matuschek
## \-   half_frame = 32;

```
target_frequency = sampling_rate*half_frame*2;
clk_src = BCM2708_CLK_SRC_OSC;
mash = BCM2708_CLK_MASH_0;
```

**Comment by koalo** [comment]
It is now configurable by the machine driver with 3.10.
