### ISSUE TITLE
Make BCLK configurable

### ISSUE THREAD

**Issue by ghost** [koalo/linux#19]
The driver should have a function that allows to configure the BCLK as master or slave with out having to modify the code.

**Comment by maximus21** [comment]
.dai_fmt in dai link description defines who is master who is slave for both BCLK and FS (LRCLK). I believe the driver processes that correctly although, perhaps, in a wrong place.

**Comment by koalo** [comment]
The selection of master and slave is implemented as usual, but the BCLK frequency configuration is not properly implemented.
