### ISSUE TITLE
bcm2708-i2s frame settings

### ISSUE THREAD

**Issue by maximus21** [koalo/linux#21]
For sample rates of 8000 x n the driver makes an assumption of frame length based on sample format forcing 40bits frame for 16 bit signal which is incompatible with many codecs. It must be a decision of the card driver, not cpu.
IMO, set_sysclk with clk_id as the frame length could be used. Then the cpu driver wouldn't have to guess.

**Comment by koalo** [comment]
Thank you for this suggestion! This would fix #18 and #19, too. I will implement this soon.

**Comment by koalo** [comment]
Is fixed in 3.10.
