### ISSUE TITLE
WM8731 in 3.10

### ISSUE THREAD

**Issue by fl4p** [koalo/linux#31]
Hi,

good job Florian, nice to see the drivers in standard rpi kernel.
Will the WM8731 be supported in 3.10?
I assume it would be possible by just copying the kernel modules from 3.8?

**Comment by koalo** [comment]
The is already a pull request for that:
https://github.com/raspberrypi/linux/pull/480

**Comment by fl4p** [comment]
Sorry, didn't see that. Will report if it's working.
