### ISSUE TITLE
WM8731 switches channels automatically

### ISSUE THREAD

**Issue by am1337** [koalo/linux#33]
I am not shure whether it is a bug in the Proto AudioCodec driver or in Alsa.

If I try to use only one channel of the soundcard as a mono device. This works ...
... temporarely.
E.g. I play sound to the left channel, it plays perfect, but after a while the sound output switches to the right channel. It toggles between the two channels every few seconds or minutes.

This is my /etc/asound.conf:
pcm_slave.asoc_out {
    pcm "hw:1,0"
    channels 2
    rate 48000
    periods 128
    period_time 0
    period_size 1024
    buffer_size 4096
}
pcm.out1 {
    type plug
    slave.pcm {
        type dshare
        ipc_key 1024
        slave asoc_out
        bindings [ 0 ]
    }
    hint {
        show on description "ASoC I2S OUT L"
    }
}
pcm.out2 {
    type plug
    slave.pcm {
        type dshare
        ipc_key 1024
        slave asoc_out
        bindings [ 1 ]
    }
    hint {
        show on description "ASoC I2S OUT R"
    }
}

I am using the device as "out1", "plug:out1" is not working.

Any idea what goes wrong?

**Comment by koalo** [comment]
When you use stereo, do the channels swap sometimes, too?

**Comment by am1337** [comment]
I will test this asap.

**Comment by am1337** [comment]
Ok, I added this to my asound.conf

pcm.out {
    type plug
    slave.pcm {
        type dshare
        ipc_key 1024
        slave asoc_out
        bindings {
                0 0 
                1 1
        }
    }
    hint {
        show on description "ASoC I2S OUT"
    }
}

and played a stereo signal via aplay (Two different sinus). The channels are also switching :-(

**Comment by koalo** [comment]
Is the WM8731 I2S master or slave?

**Comment by am1337** [comment]
Afaik it is slave.

**Comment by koalo** [comment]
Is it the original proto board or an own hardware?

**Comment by am1337** [comment]
Own hardware with the same wiring. But I can test the original proto board.

**Comment by koalo** [comment]
When you use the original driver, there is SND_SOC_DAIFMT_CBM_CFM so the **C** odec is **B** it **M** aster and **C** odec is **F** rame **M** aster and that is preferred.

Is there any dropout, buffer overrun/underrun at the same time the channels swap?

**Comment by am1337** [comment]
Testing took a while because it is realy weird.

I am using the original driver of kernel 3.8. I tested the proto board and mine. First I thought they behave different, but they don't. Only the channel switching intervall on the protoboard is much faster (You only hear a short noise). I recorded a signal with 440Hz on one channel and 1KHz on the other.

![switch](https://cloud.githubusercontent.com/assets/5406534/2717569/77e033be-c542-11e3-896c-5f45d2c0a7c3.png)

There is no buffer underrun or overrun. The wires for the proto board are about 5cm long. The circuit path on my board are just a little bit longer.

**Comment by koalo** [comment]
Can you create a oscillogram of the frame sync (directly at the raspberry and at the WM8731)?

Another unrelated thing to test: Someone complained that it is not possible to let the driver run for several days (or with coherent_pool=1M for 6.5 hours). Can you verify this?

**Comment by am1337** [comment]
I had the driver running last nigth, beside of the channel switching there were no problems.

I will check the fs with the oscilloscope now.

**Comment by am1337** [comment]
It is not possible to record the whole fs signal with my scope, so I can't check whether the signal looks different when channels are switching. 
But I made a screenshot of the fs signal. It looks very good. No reason why it could disturb communication.
![tek0029](https://cloud.githubusercontent.com/assets/5406534/2720214/5230805e-c56c-11e3-9447-bd6206138a24.png)
The blue line is recorded at the Pi, the yellow one at the codec's side.

**Comment by koalo** [comment]
The signal looks good.

Maybe you could try the current branch:
https://github.com/koalo/linux/tree/rpi-3.10.y

**Comment by am1337** [comment]
ok, but first I have to port the driver to 3.10, right?

**Comment by koalo** [comment]
nope - BBUK has done this already
https://github.com/koalo/linux/blob/rpi-3.10.y/sound/soc/bcm/rpi-proto.c

**Comment by am1337** [comment]
great

**Comment by am1337** [comment]
I tested rpi-3.10.y now (I thought the driver wasn't ported yet, as I only tried rpi-3.10.y-asoc before).

Good news: The codec seems not to do any channel switching now (only a short test).

But now my asound.conf doesn't work anymore. I will check this after easter holidays next week.

Many thanks for your help!

**Comment by koalo** [comment]
I am happy to hear that. Please test the long time stability again with this driver just to be sure there was no error introduced with this version.

**Comment by am1337** [comment]
I have to reopen that issue. The problem wasn't mmap. The error just does not always appear.

After some (much) more troubleshooting I think, that the channels of LineOut and LineIn swap if there is a glitch in the frame selection signal. It can be caused by the power supply or other effects.
If the frame signal is disconnected and reconnected again, the channels are often swapped. That means that the bytestream is not correctly synchronised to the frame select signal.

The wm8731 is used as Bit-Master and Frame-Master as koalo mentioned above. If I configure it as slave, the channels are synchronised correctly. After reconnecting the frame select signal the channels are always in the right order. We just changed one parameter of the kernel module:

diff --git a/sound/soc/bcm/rpi-proto.c b/sound/soc/bcm/rpi-proto.c
index 70b0166..91f00a3 100644
--- a/sound/soc/bcm/rpi-proto.c
+++ b/sound/soc/bcm/rpi-proto.c
@@ -82,7 +82,8 @@ static struct snd_soc_dai_link snd_rpi_proto_dai[] = {
        .codec_name     = "wm8731.1-001a",
        .dai_fmt        = SND_SOC_DAIFMT_I2S
                                | SND_SOC_DAIFMT_NB_NF
-                               | SND_SOC_DAIFMT_CBM_CFM,
-                               | SND_SOC_DAIFMT_CBS_CFS,
-                               //| SND_SOC_DAIFMT_CBM_CFM,
      .ops            = &snd_rpi_proto_ops,
  },
  };

But now we have the problem that the LineIn signal has always some click noise on left channel. I recorded some silence below:
![arecord](https://cloud.githubusercontent.com/assets/5406534/3626746/148980c6-0e81-11e4-9255-21531c6ec189.png)

I know that the Pi's clk doesn't fit perfect for the custom sample rates, but the signal shouldn't be that bad.

Does anyone have an idea what could cause:
- the disruption of the sound signal?
- the synchronisation problem if DAC is used as bit and frame master?

**Comment by am1337** [comment]
I found some new hints about channel swapping. The SOC datasheet (http://www.raspberrypi.org/wp-content/uploads/2012/02/BCM2835-ARM-Peripherals.pdf) says on page 121-122:

"If a FIFO error occurs in a two channel frame, then channel synchronisation may be lost which may result in a left right audio channel swap. RXSYNC and TXSYNC status bits are provided to help determine if channel slip has occurred. They indicate if the number of words in the FIFO is a multiple of a full frame (taking into account where we are in the current frame being transferred). This assumes that an integer number of frames data has been sent/read from the FIFOs."

I am wondering why it does not automatically sync L to low and R to high?

**Comment by am1337** [comment]
Hi all,

I still have another question about channel swapping: I changed CODEC to Bit-Slave and Frame-Slave (CBS_BFS instead of CBM_CFM). Now I can interrupt Frame-Clock or Bit-Clock signals and audio will always be recovered correctly. No channels are swapped after these interruptions.
But sometimes channels still swap without doing anything with the clock signals. So this is not the only issue that can cause channel swapping.
Which signal/wire could also cause a channel swap and how? I don't think my wires are to long and also my pcb-version looks well.
Or may be this is not an hardware issue and there is still something incorrect in one of the used kernel modules?
I tried to use MMAP and also disabled it. I disabled 24 Bit and 32 Bit support and tried CBS_CFS and CBM_CFM but nothing helped to avoid channel swapping permanently. 

Any more ideas?

**Comment by am1337** [comment]
Another nice testing result: 
If I only use output, channels are swapping very often. If I also use input, input channels are ok, output channels only have some few interrupts <1s. If output channels are swapped this will suddenly be fixed if I activate input.
Tested with: SND_SOC_DAIFMT_CBS_CFS

A short test with SND_SOC_DAIFMT_CBM_CFM showed the same behavior.

**Comment by am1337** [comment]
We ported driver to kernel 3.12. Now it works (test is running since 3 days now). It seems that high io load on 3.8 and 3.10 caused channel switching.
