### ISSUE TITLE
Add 32 bit support - Done, but needs testing!

### ISSUE THREAD

**Issue by koalo** [koalo/linux#4]

**Comment by koalo** [comment]
Please test it with the current kernel

**Comment by steveha8838** [comment]
Recompiled the 06 May Version.  Left-Right Channels were swapped.  Gain has increased and is normal 
now.  Sound quality is better than before.  I tested some hi-resolution files and still showing 16 bits mode and ill 96khz.  Anyway,  how to turn on 32 bit support ?

**Comment by koalo** [comment]
I think the channels were swapped before and it is now right. At least for my codec this is the case.

For testing 32 bit support and higher bitrates, I will upload the ess9018 driver soon.

**Comment by steveha8838** [comment]
Are you thinking of providing a driver set of supported DACs and we can just modprobe the corresponding dac on startup ?

**Comment by koalo** [comment]
Yes? 
Better way would be using device tree, but I didn't get that running.

**Comment by koalo** [comment]
As steveha8838 reported in issue #1 32 bit runs smoothly (or at least 24 bit files via 32 bit mode)
